import ToasterContext from "./context/ToasterContext";
import "./globals.css";
import { Jost } from "next/font/google";

const jost = Jost({
  weight: ["300", "400", "500", "600", "700", "800"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Talkative",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <ToasterContext />
        {children}
      </body>
    </html>
  );
}
